value1=input("Bir değer giriniz:")
print(value1 , type(value1))
value2=int(input("bir sayi giriniz:"))
print(value2 , type(value2))
value3=float(input("bir float değer giriniz:"))
print(f'value:{value3 }', type(value3))
value4=input("Bir string ifade giriniz:")
print(f'Hello {value4}!',type(value4))
value5=input("bir string ifade giriniz:")
print(f'Python {value5}', type(value5))
